# Message
MSG_YOUR_KILLS: '&a%playername% &7ha &a%mykills% &7uccisioni.'
MSG_OTHER_KILLS: '&a%othername% &7ha &a%otherkills% &7uccisioni.'
MSG_NO_KILLS: '&a%othername% &7 non risulta sui nostri registri.
MSG_RELOAD: '&7Reload Completato.'

Rank:
  A:
    Player_To_Kill: 10
    Pex_Group: ''
  B:
    Player_To_Kill: 20
    Pex_Group: ''
  C:
    Player_To_Kill: 30
    Pex_Group: ''
  D:
    Player_To_Kill: 40
    Pex_Group: ''
  E:
    Player_To_Kill: 50
    Pex_Group: ''
