Rank:
  A:
    Player_To_Kill: 10
    Pex_Group: ''
  B:
    Player_To_Kill: 20
    Pex_Group: ''
  C:
    Player_To_Kill: 30
    Pex_Group: ''
  D:
    Player_To_Kill: 40
    Pex_Group: ''
  E:
    Player_To_Kill: 50
    Pex_Group: ''