name: SharkRank
version: 2.0
Author: Numixe & GiantRaven
main: it.sharkcraft.sharkrank.SharkRank
commands:
        shrank:
          description: View Kill
        kill:
          description: Alias of /shrank .
        shreload:
          description: Reload Config
        killset:
          description: Set New Kill