name: SharkRank
version: 0.32.8
Author: Numixe & GiantRaven
main: it.sharkcraft.sharkrank.SharkRank
commands:
        shrank:
          description: View Kill
        kill:
          description: Alias of /shrank .
        shreload:
          description: Reload Config